version: "3"

services:
  web:
    build: .
    container_name: books-challenge
    restart: always
    volumes:
      - ./:/books
    ports:
      - 3000:3000
    command:
      - /bin/sh
      - -c
      - |
        yarn dev

  book:
    build: .
    container_name: books-challenge-story
    restart: always
    volumes:
      - ./:/books
    ports:
      - 6006:6006
    command:
      - /bin/sh
      - -c
      - |
        yarn storybook
