version: "3"

services:
  web:
    build: .
    container_name: iosasys
    restart: always
    volumes:
      - ./:/books
    ports:
      - 5173:5173
    command:
      - /bin/sh
      - -c
      - |
        yarn dev

  book:
    build: .
    container_name: iosasys-book
    restart: always
    volumes:
      - ./:/books
    ports:
      - 6006:6006
    command:
      - /bin/sh
      - -c
      - |
        yarn storybook
